language: cpp
os: osx

compiler: clang

env:
  global:
  - WORKSPACE=$TRAVIS_BUILD_DIR
  - Configuration=Default
  - SDK_VERSION=Default
  - XBMC_DEPENDS_ROOT=Default
  - DARWIN_ARM_CPU=Default
  - BUILDTHREADS=3
  - MAKEFLAGS=-w

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pv ; fi

script:
- ./tools/buildsteps/ios/prepare-depends 2>&1 | pv -p -t -e -l -s 280 >build.log
- ./tools/buildsteps/ios/configure-depends 2>&1 | pv -p -t -e -l -s 88 >>build.log
- ./tools/buildsteps/ios/make-depends 2>&1 | pv -n -t -e -l -s 76319 >>build.log
#- ./tools/buildsteps/ios/prepare-xbmc >>build.log 2>&1
#- ./tools/buildsteps/ios/configure-xbmc >>build.log 2>&1
#- ./tools/buildsteps/ios/make-xbmc >>build.log 2>&1

after_failure:
- tail build.log

git:
  depth: 3
